@baseUrl={{$dotenv API}}
@email={{$dotenv EMAIL}}
@password={{$dotenv PASSWORD}}
@code={{$dotenv CODE}}
@id={{$dotenv ID}}
# @name available
GET {{baseUrl}}/auth/l@email.test HTTP/1.1
Content-Type: application/json

###

# @name login
POST {{baseUrl}}/auth/ HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "remember": false
}

###

# @name verify
PUT {{baseUrl}}/auth/ HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

{
  "code": "{{code}}"
}

###

@cookie = {{login.response.headers.set-cookie}}

# @name logout
DELETE {{baseUrl}}/auth/ HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

# @cookie = {{logout.response.headers.set-cookie}}

###

# @name createCode
POST {{baseUrl}}/codes/ HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

###

# @name createUser
POST {{baseUrl}}/users/ HTTP/1.1
Content-Type: application/json

{
  "firstName": "Luc",
  "lastName": "Huynh Tan",
  "email": "{{email}}",
  "password": "{{password}}",
  "day": 29,
  "month": 9,
  "year": 1997,
  "sex": "Male"
}

###

# @name readUser
GET {{baseUrl}}/users/ HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

###

# @name createFolder
POST {{baseUrl}}/folders/ HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

{
  "path": "/home",
  "name": "test"
}

###

# @name readFolder
GET {{baseUrl}}/folders/{{id}} HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

###

# @name updateFolder
PUT {{baseUrl}}/folders/{{id}} HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

{
  "name": "New folder"
}

###

# @name deleteFolder
PATCH {{baseUrl}}/folders/{{id}} HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

###

# @name restoreFolder
PATCH {{baseUrl}}/folders/r/{{id}} HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

###

# @name listFolders
GET {{baseUrl}}/folders/ HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

###
